// GENERATED by scripts/gen_contracts_ts.py from contracts/v3/view-service.schema.json and
// contracts/v3/commands.json (protocol loomward/3). Do not edit; run
// `py -3 scripts/gen_contracts_ts.py` and commit the result.
//
// Byte quantities are decimal strings (`ByteCount`); `null` means unknown, never zero.
// Counts are JSON integers below 2^53. No request carries a path. A type match is never
// permission: the service re-validates scope, grants and bounds.

export const PROTOCOL = "loomward/3";

// ---- $defs

export type Protocol = "loomward/3";

export type RequestId = string;

export type CommandName = string;

export type RootId = string;

export type VolumeId = string;

/** Opaque, session-tagged. Identifies a catalogue row for viewing only; never an effect operand (invariant 5). */
export type NodeId = string;

export type JobId = string;

export type GrantId = string;

export type CollectionId = string;

export type ProposalId = string;

export type SubscriptionId = string;

export type PreviewId = string;

/** Encodes pid plus process start time so PID reuse cannot alias. Observation only. */
export type ProcessRef = string;

export type ModelId = string;

export type EventId = string;

export type GroupId = string;

/** Opaque; bound to command, query, anchor, generation and session. Not reusable for another scope. */
export type Cursor = string;

export type Digest = string;

/** Exact unsigned decimal. All byte quantities on the wire use this, never JSON numbers (ADR-V3-04). Range 0..18446744073709551615 (u64::MAX) is enforced at runtime (semantics.md section 9); the pattern alone admits larger 20-digit strings. */
export type ByteCount = string;

/** null means unknown, never zero (invariant 4). Same runtime range as ByteCount. */
export type NullableBytes = string | null;

export type Generation = string;

export type NullableGeneration = string | null;

export type Count = number;

export type NullableCount = number | null;

export type Fraction = number;

export type NullableFraction = number | null;

/** Display-only per-second rate; null until two samples exist. */
export type NullableRate = number | null;

/** RFC 3339 in UTC with a literal Z; display and chronology only. Servers emit millisecond precision. */
export type Timestamp = string;

export type NullableTimestamp = string | null;

/** Random per service start; event seq is only comparable within one epoch (semantics.md section 7). */
export type StreamEpoch = string;

/** 0 is fastest, 9 slowest; demotion goes to an equal or higher number (planner v1/v2 rule). */
export type Tier = number;

export type NullableTier = number | null;

export type Label = string;

/** One catalogue file per class; a session serves exactly one (ADR-V3-15). */
export type DatasetClass = "synthetic" | "personal";

export type Basis = "logical" | "allocated";

export type CoverageState = "complete" | "partial" | "stale" | "unscanned" | "denied" | "excluded" | "cancelled" | "unknown";

/** Default pending the LW-101 spike: file_id_extd_directory_info (ADR-V3-05). */
export type EnumerationStrategy = "file_id_extd_directory_info" | "nt_query_directory_file_ex" | "find_first_file_ex_large_fetch" | "std_read_dir";

export type ExtFamily = "document" | "spreadsheet" | "presentation" | "image" | "video" | "audio" | "archive" | "code" | "data" | "model" | "executable" | "system" | "font" | "other" | "none";

export type FileAttribute = "readonly" | "hidden" | "system" | "archive" | "compressed" | "sparse" | "encrypted" | "offline" | "not_content_indexed" | "reparse_point" | "recall_on_open" | "recall_on_data_access" | "pinned" | "unpinned" | "temporary";

export type EntryFlag = "sensitive_name" | "protected_context" | "hardlink_suspected" | "cloud_placeholder" | "reparse_not_followed" | "excluded_state_dir" | "access_denied" | "enumeration_error" | "identity_unavailable" | "name_lossy" | "on_disk_only_listing" | "listing_incomplete";

/** Display only. Never accepted back as input; no command takes a path string. */
export interface DisplayPath {
  text: string;
  truncated: boolean;
}

export type ErrorCode = "invalid_request" | "unsupported_protocol" | "unknown_command" | "not_found" | "permission_denied" | "capability_unavailable" | "stale_generation" | "device_offline" | "partial_coverage" | "resource_budget" | "busy" | "cancelled" | "deadline_exceeded" | "internal_error";

export interface ErrorBody {
  code: ErrorCode;
  message: string;
  retryable: boolean;
  detail: Record<string, unknown> | null;
}

export interface RequestEnvelope {
  protocol: Protocol;
  request_id: RequestId;
  command: CommandName;
  /** Validated against the request definition named for this command in commands.json. */
  payload: Record<string, unknown>;
  deadline_ms?: number;
  expected_generation?: Generation;
  /** Revision precondition for owner-state mutations (volumes.declare_tier, collections.update_members): the call commits only while state.db is still at this revision, else stale_generation with detail.reason state_rev_changed (semantics.md sections 3 and 5). Elsewhere invalid_request. */
  expected_state_rev?: Generation;
}

export interface ResponseMeta {
  served_at: Timestamp;
  elapsed_ms: Count;
  dataset_class: DatasetClass;
  budget_hit: boolean;
  /** Catalogue revision the response was read at, or committed at for a mutation (semantics.md section 5). */
  catalog_rev: NullableGeneration;
  /** state.db revision the response was read at, or committed at for a mutation; null when the command touched no state.db data (semantics.md section 5). */
  state_rev: NullableGeneration;
}

export interface ResponseOk {
  protocol: Protocol;
  request_id: RequestId;
  ok: true;
  result: Record<string, unknown>;
  meta: ResponseMeta;
}

export interface ResponseError {
  protocol: Protocol;
  request_id: RequestId | null;
  ok: false;
  error: ErrorBody;
  meta?: ResponseMeta;
}

export type ResponseEnvelope = ResponseOk | ResponseError;

export type EventName = "stream.hello" | "stream.lagged" | "job.state" | "scan.progress" | "tree.invalidated" | "telemetry.sample" | "learning.updated" | "roots.changed" | "volumes.changed" | "health.warning";

export interface EventEnvelope {
  protocol: Protocol;
  epoch: StreamEpoch;
  seq: Count;
  event: EventName;
  at: Timestamp;
  /** Emitted only after the change it describes is committed (semantics.md section 6). */
  catalog_rev: NullableGeneration;
  /** state.db revision of the commit the event describes; null for events about catalogue-only changes or telemetry. */
  state_rev: NullableGeneration;
  /** Validated against the event definition named in commands.json; L1 generates discriminated envelope validation from commands.json (semantics.md section 10). */
  data: Record<string, unknown>;
}

export type EmptyRequest = Record<string, unknown>;

export interface Capabilities {
  observation: {
    metadata_scan: boolean;
    process_observation: boolean;
    gpu_observation: boolean;
    disk_io_observation: boolean;
    teacher_disclosure: boolean;
  };
  effects: {
    file_move: false;
    file_delete: false;
    file_rename: false;
    file_write: false;
    content_read: false;
    process_kill: false;
    process_suspend: false;
    process_priority: false;
    memory_trim: false;
    uninstall: false;
    elevation: false;
  };
}

export interface SessionInfo {
  protocol: Protocol;
  engine_version: string;
  adapter: "tauri" | "http";
  dataset_class: DatasetClass;
  session_started_at: Timestamp;
  enumeration_strategy: EnumerationStrategy;
  capabilities: Capabilities;
  features: {
    grant_picker: boolean;
    disclosure_dialog: boolean;
    teacher_available: boolean;
    telemetry_available: boolean;
    gpu_available: boolean;
  };
  limits: {
    max_request_bytes: Count;
    max_slice_nodes: Count;
    max_page_items: Count;
  };
}

export interface HealthWarning {
  code: "catalog_writer_backlog" | "low_state_disk" | "scan_throttled" | "telemetry_unavailable" | "teacher_failed" | "root_identity_changed" | "event_stream_lagging";
  message: string;
  at: Timestamp;
}

export interface Health {
  observed_at: Timestamp;
  engine: {
    /** PROCESS_MEMORY_COUNTERS_EX2.PrivateUsage. */
    private_commit_bytes: NullableBytes;
    working_set_bytes: NullableBytes;
    cpu_seconds: number | null;
    threads: NullableCount;
  };
  catalog: {
    schema_version: number;
    db_bytes: NullableBytes;
    wal_bytes: NullableBytes;
    files: Count;
    dirs: Count;
    writer_queue_depth: Count;
    writer_queue_capacity: Count;
  };
  jobs_running: Count;
  last_error: ErrorBody | null;
  warnings: HealthWarning[];
}

export interface RootScanState {
  state: "never_scanned" | "scanning" | "complete" | "partial" | "stale" | "failed";
  last_job_id: JobId | null;
  generation: NullableGeneration;
  finished_at: NullableTimestamp;
  coverage: CoverageState;
}

export interface SubtreeTotals {
  /** Directory entries (names), not objects. */
  files: Count;
  dirs: Count;
  /** Bytes by directory entry: sum of default-stream end-of-file as listed. A hard-linked object counts once per observed name. */
  logical_bytes: ByteCount;
  /** Bytes by directory entry: sum of default-stream allocation as listed. */
  allocated_bytes: NullableBytes;
  allocation_unknown_files: Count;
  skipped: Count;
  failed: Count;
  complete: boolean;
  /** Alternate data streams and filesystem metadata are not observed in v0.3. */
  stream_coverage: "default_stream_only";
  /** Distinct (volume_key, file_id) objects within this subtree; null when any entry lacks a native ID. */
  unique_objects: NullableCount;
  /** Allocation counted once per unique object within this subtree; null when unique_objects is null or allocation is unknown. */
  unique_allocated_bytes: NullableBytes;
  /** Entries whose object has another observed name anywhere in the dataset or an observed link count above 1. */
  multi_link_entries: Count;
}

export interface Root {
  root_id: RootId;
  display_path: DisplayPath;
  origin: "fixture" | "lab_generated" | "owner_granted";
  dataset_class: DatasetClass;
  volume_id: VolumeId | null;
  granted_at: Timestamp;
  granted_via: "desktop_picker" | "cli_flag" | "fixture";
  grant_state: "active" | "revoked" | "identity_changed";
  scan: RootScanState;
  totals: SubtreeTotals | null;
}

export interface RootList {
  roots: Root[];
}

/** Tauri adapter only. Rust opens the native folder picker; the webview never supplies a path. */
export interface RootGrantRequest {
  purpose: "metadata_scan";
}

export interface RootGrantResult {
  outcome: "granted" | "cancelled_by_user" | "refused";
  root: Root | null;
  refusal: null | "volume_root" | "reparse_or_placeholder" | "not_a_directory" | "contains_state_dir" | "inside_state_dir" | "already_granted" | "network_or_removable_unsupported" | "identity_unavailable" | "synthetic_session_requires_lab_root";
}

export interface RootRevokeRequest {
  root_id: RootId;
  /** Deletes Loomward's own catalogue rows for the root. Never touches the scanned files. */
  purge_catalog: boolean;
}

export interface RootRevokeResult {
  root_id: RootId;
  revoked_at: Timestamp;
  purged: boolean;
}

/** A hint about the device, not a measured speed (docs/07). */
export interface DeviceHint {
  bus_type: "nvme" | "sata" | "sas" | "scsi" | "usb" | "raid" | "virtual" | "sd" | "other" | "unknown";
  seek_penalty: boolean | null;
  multiple_disks: boolean | null;
  basis: "ioctl_storage_query_property" | "unavailable";
}

export interface TierInfo {
  tier: NullableTier;
  basis: "declared" | "device_hint" | "unknown";
  declared_tier: NullableTier;
  hint_tier: NullableTier;
  note: string;
}

export interface VolumeFeatures {
  file_ids_128: boolean | null;
  hard_links: boolean | null;
  sparse_files: boolean | null;
  compression: boolean | null;
  reparse_points: boolean | null;
  usn_journal: boolean | null;
}

export interface Volume {
  volume_id: VolumeId;
  display_name: string;
  mount_points: string[];
  filesystem: string | null;
  label: string | null;
  online: boolean;
  read_only: boolean | null;
  removable: boolean | null;
  capacity_bytes: NullableBytes;
  free_bytes: NullableBytes;
  device: DeviceHint;
  tier: TierInfo;
  features: VolumeFeatures;
  observed_at: Timestamp;
}

export interface VolumeList {
  volumes: Volume[];
}

/** Records a human preference. null clears the declaration. */
export interface DeclareTierRequest {
  volume_id: VolumeId;
  tier: NullableTier;
}

export interface DeclareTierResult {
  volume: Volume;
  preference_recorded_at: Timestamp;
}

/** placement.simulate is synchronous and bounded, never a job (semantics.md section 2). */
export type JobKind = "scan" | "refit" | "teacher";

export type JobState = "queued" | "running" | "cancel_requested" | "cancelled" | "failed" | "completed";

export interface ScanBudget {
  max_entries?: number;
  max_dirs?: number;
  threads?: number;
}

export interface ScanStartRequest {
  root_id: RootId;
  mode: "full" | "refresh";
  budget?: ScanBudget;
}

export interface ScanProgress {
  phase: "queued" | "enumerating" | "committing" | "rolling_up" | "sweeping" | "finalising" | "done";
  strategy: EnumerationStrategy;
  examined: Count;
  indexed_files: Count;
  indexed_dirs: Count;
  skipped: Count;
  failed: Count;
  logical_bytes: ByteCount;
  allocated_bytes: NullableBytes;
  pending_dirs: Count;
  writer_queue_depth: Count;
  entries_per_second: number;
  elapsed_ms: Count;
  limit_hit: boolean;
}

export interface Job {
  job_id: JobId;
  kind: JobKind;
  state: JobState;
  root_id: RootId | null;
  created_at: Timestamp;
  started_at: NullableTimestamp;
  finished_at: NullableTimestamp;
  progress: ScanProgress | null;
  coverage: CoverageState | null;
  error: ErrorBody | null;
}

export interface JobRefRequest {
  job_id: JobId;
}

export interface JobResult {
  job: Job;
}

export interface JobListRequest {
  kinds?: JobKind[];
  limit: number;
}

export interface JobList {
  jobs: Job[];
}

/** What the owner or a model thinks this is. A suggestion is not an approval (invariant 3). */
export interface MeaningThread {
  state: "labelled" | "suggested" | "mixed" | "none" | "pending" | "unknown";
  label: Label | null;
  share: NullableFraction;
  source: null | "human" | "student" | "teacher";
  collection_ids: CollectionId[];
}

/** Where the bytes physically are. */
export interface ResidencyThread {
  volume_id: VolumeId | null;
  tier: NullableTier;
  tier_basis: "declared" | "device_hint" | "unknown";
}

/** What Loomward may observe. In v0.3 no thread state ever implies an effect permission. */
export interface PermissionThread {
  state: "granted" | "partial" | "excluded" | "denied" | "revoked" | "unknown";
  reason: null | "metadata_grant_active" | "sensitive_name" | "protected_context" | "cloud_placeholder" | "reparse_not_followed" | "access_denied" | "grant_revoked" | "not_scanned" | "mixed_children";
}

export interface Threads {
  meaning: MeaningThread;
  residency: ResidencyThread;
  permission: PermissionThread;
}

export type Anchor = {
  kind: "atlas";
} | {
  kind: "root";
  root_id: RootId;
} | {
  kind: "node";
  node_id: NodeId;
};

export interface TreeSliceRequest {
  anchor: Anchor;
  depth: number;
  max_nodes: number;
  min_share: number;
  basis: Basis;
  include_files: boolean;
}

export interface SliceNode {
  node_id: NodeId;
  /** Index into TreeSlice.nodes; null only for the anchor at index 0. Parents always precede children. */
  parent: number | null;
  kind: "atlas" | "volume" | "root" | "dir" | "file" | "other";
  name: string;
  depth: number;
  /** Size under the requested basis. Under allocated basis, entries with unknown allocation contribute 0 here and are counted in size_unknown_files. */
  size_bytes: ByteCount;
  size_unknown_files: Count;
  logical_bytes: ByteCount;
  allocated_bytes: NullableBytes;
  files: Count;
  dirs: Count;
  child_count: NullableCount;
  /** Only for kind=other: how many siblings were folded into this node. */
  folded_count: NullableCount;
  coverage: CoverageState;
  /** True while a scan is still adding to this subtree. */
  live: boolean;
  ext_family: ExtFamily | null;
  modified_at: NullableTimestamp;
  threads: Threads;
}

export interface RootGeneration {
  root_id: RootId;
  generation: NullableGeneration;
}

export interface TreeSlice {
  anchor_node_id: NodeId;
  basis: Basis;
  root_generations: RootGeneration[];
  complete: boolean;
  live: boolean;
  /** consistent: every directory sum was published at a revision covering its committed listings. provisional_live: sums come from the running scan's arena snapshot; 'other' nodes are clamped at zero. Inconsistent committed sums are repaired before serving, never sent. */
  aggregate_state: "consistent" | "provisional_live";
  ordering: "exact" | "approximate_live";
  truncated: boolean;
  nodes: SliceNode[];
}

export interface MeaningRequest {
  node_ids: NodeId[];
}

export interface MeaningResult {
  model_id: ModelId | null;
  items: {
    node_id: NodeId;
    meaning: MeaningThread;
  }[];
  budget_hit: boolean;
}

export interface EntryRow {
  node_id: NodeId;
  kind: "dir" | "file";
  name: string;
  extension: string | null;
  ext_family: ExtFamily | null;
  logical_bytes: ByteCount;
  allocated_bytes: NullableBytes;
  files: NullableCount;
  dirs: NullableCount;
  modified_at: NullableTimestamp;
  attributes: FileAttribute[];
  flags: EntryFlag[];
  coverage: CoverageState;
  /** Search and collection results only: the parent's display path. */
  location_hint: DisplayPath | null;
}

export interface TreeChildrenRequest {
  node_id: NodeId;
  /** size_desc is index-backed for both bases (ties broken by row id). name_asc and modified_desc are served only for directories with at most 10,000 direct children; larger ones return resource_budget with detail sort_requires_index. */
  sort: "size_desc" | "name_asc" | "modified_desc";
  basis: Basis;
  limit: number;
  cursor: Cursor | null;
}

export interface EntryPage {
  anchor: NodeId | CollectionId | null;
  generation: NullableGeneration;
  items: EntryRow[];
  next_cursor: Cursor | null;
  total: NullableCount;
  budget_hit: boolean;
}

export interface NodeRefRequest {
  node_id: NodeId;
}

export interface NodePath {
  root_id: RootId | null;
  ancestors: ({
    node_id: NodeId;
    kind: "atlas" | "volume" | "root" | "dir" | "file";
    name: string;
  })[];
  truncated: boolean;
}

export interface IdentityObservation {
  /** Width is preserved: a 64-bit ID is never padded and reported as 128-bit. */
  quality: "native_file_id_128" | "native_file_id_64" | "path_observation" | "unavailable";
  /** Whether labels and collection membership may bind to this object (docs/41 section 6.3). Without it, feedback.record returns capability_unavailable. */
  durable_reference: "available" | "unavailable_identity_quality" | "unavailable_filesystem";
  volume_key: string | null;
  file_id_hex: string | null;
  observed_generation: NullableGeneration;
  authorises_effects: false;
}

/** Scores are uncalibrated relative scores, not probabilities (invariant 4). */
export interface Suggestion {
  node_id: NodeId;
  model_id: ModelId;
  ranked: {
    label: Label;
    score: Fraction;
  }[];
  abstain: boolean;
  reasons: ("no_training_examples" | "insufficient_human_support" | "unfamiliar_features" | "ambiguous_model_scores" | "sensitive_excluded")[];
  feature_coverage: Fraction;
  review_priority: Fraction;
  calibrated: false;
  autonomy_allowed: false;
  teacher: TeacherLabel | null;
}

export interface CollectionRef {
  collection_id: CollectionId;
  name: string;
}

export interface NodeDetail {
  row: EntryRow;
  root_id: RootId;
  volume_id: VolumeId | null;
  display_path: DisplayPath;
  identity: IdentityObservation;
  timestamps: {
    created_at: NullableTimestamp;
    modified_at: NullableTimestamp;
    changed_at: NullableTimestamp;
    accessed_at: NullableTimestamp;
    accessed_note: string;
  };
  subtree: SubtreeTotals | null;
  threads: Threads;
  exclusions: {
    code: EntryFlag;
    explanation: string;
  }[];
  denied_capabilities: ({
    capability: "file_move" | "file_delete" | "file_rename" | "content_read" | "teacher_disclosure" | "training";
    reason: "not_implemented_in_v03" | "sensitive_name" | "excluded" | "no_grant" | "cloud_placeholder";
  })[];
  memberships: CollectionRef[];
  suggestion: Suggestion | null;
}

export interface SearchRequest {
  root_id: RootId | null;
  text: string;
  extension: string | null;
  min_bytes: NullableBytes;
  kind: "any" | "file" | "dir";
  limit: number;
  cursor: Cursor | null;
}

export interface BreakdownRequest {
  node_id: NodeId;
  by: "ext_family" | "extension" | "age_band";
  basis: Basis;
  limit: number;
}

export interface BytesAndFiles {
  bytes: ByteCount;
  files: Count;
}

export interface Breakdown {
  node_id: NodeId;
  by: "ext_family" | "extension" | "age_band";
  basis: Basis;
  generation: NullableGeneration;
  complete: boolean;
  buckets: {
    key: string;
    label: string;
    bytes: ByteCount;
    files: Count;
  }[];
  other: BytesAndFiles;
  unknown: BytesAndFiles;
}

export interface Taxonomy {
  version: number;
  labels: Label[];
}

/** label is null only when retract is true (service-enforced); the service stores the withdrawn label internally (docs/41 section 9.1). client_event_id is a durable idempotency key: identical replay returns the original result, reuse with different content is invalid_request. Records a human label; never a grant. */
export interface FeedbackRequest {
  node_id: NodeId;
  label: Label | null;
  retract: boolean;
  client_event_id: string;
}

export interface LearningStatus {
  model_id: ModelId | null;
  algorithm: "weighted_multinomial_nb_v1";
  taxonomy_version: number;
  training_count: Count;
  human_events: Count;
  teacher_labels: Count;
  human_support: { [key: string]: Count };
  fitted_at: NullableTimestamp;
  dataset_class: DatasetClass;
  calibrated: false;
  autonomy_allowed: false;
}

export interface FeedbackResult {
  event_id: EventId;
  revision: number;
  /** True when client_event_id matched an already committed identical event; nothing new was written. */
  idempotent_replay: boolean;
  data_class: "human";
  learning: LearningStatus;
}

export interface LearningQueueRequest {
  root_id: RootId | null;
  limit: number;
  cursor: Cursor | null;
}

export interface LearningQueue {
  model_id: ModelId | null;
  items: {
    row: EntryRow;
    suggestion: Suggestion;
  }[];
  next_cursor: Cursor | null;
}

/** Virtual membership in Loomward's own database. Never moves, links or renames a file. */
export interface Collection {
  collection_id: CollectionId;
  name: string;
  kind: "human" | "label_view";
  member_count: Count;
  logical_bytes: ByteCount;
  created_at: Timestamp;
}

export interface CollectionList {
  collections: Collection[];
}

export interface CollectionCreateRequest {
  name: string;
}

export interface CollectionMembersUpdate {
  collection_id: CollectionId;
  add: NodeId[];
  remove: NodeId[];
}

export interface CollectionMembersRequest {
  collection_id: CollectionId;
  limit: number;
  cursor: Cursor | null;
}

export type TeacherField = "name" | "extension" | "context" | "size_bucket";

/** The only v0.3 teacher: GPT-6.1 Sol at medium effort via the owner's local Codex CLI. A cloud recipient. */
export type TeacherRecipient = "codex_cli_gpt_6_1_sol";

export interface TeacherPreviewRequest {
  node_ids: NodeId[];
  recipient: TeacherRecipient;
}

/** Immutable once created. Shows the complete request that would leave the machine. Creating a preview sends nothing. */
export interface TeacherPreview {
  preview_id: PreviewId;
  serialization_version: "loomward-teacher-request/1";
  /** The exact system instructions sent. */
  instructions: string;
  allowed_labels: Label[];
  output_schema_digest: Digest;
  /** Pinned Codex executable hash, version, argv and effective configuration overrides (docs/41 section 9.2). */
  runner_profile_digest: Digest;
  recipient: TeacherRecipient;
  model: "gpt-6.1-sol";
  reasoning_effort: "medium";
  dataset_class: DatasetClass;
  fields: TeacherField[];
  items: {
    /** Request-local handle; catalogue IDs never leave the machine. */
    handle: string;
    metadata: {
      name: string;
      extension: string;
      context: string;
      size_bucket: number;
    };
  }[];
  excluded: ({
    node_id: NodeId;
    reason: "sensitive_name" | "sensitive_context" | "excluded" | "cloud_placeholder" | "directory_not_supported";
  })[];
  taxonomy_version: number;
  payload_bytes: Count;
  /** SHA-256 over the canonical serialization of the complete request: instructions, allowed labels, output schema, items and serialization version. */
  payload_digest: Digest;
  expires_at: Timestamp;
}

/** Built by Rust from the stored immutable preview, never from UI input, and rendered by the native confirmation dialog item by item. Not sent over the wire; defined here so the Rust and dialog implementations agree. */
export interface DisclosureSummary {
  preview_id: PreviewId;
  recipient: TeacherRecipient;
  model: "gpt-6.1-sol";
  reasoning_effort: "medium";
  dataset_class: DatasetClass;
  fields: TeacherField[];
  items: {
    handle: string;
    name: string;
    extension: string;
    context: string;
    size_bucket: number;
  }[];
  excluded_count: number;
  payload_digest: Digest;
  runner_profile_digest: Digest;
  expires_at: Timestamp;
}

/** Personal dataset: the Tauri adapter shows a native confirmation dialog from Rust; the HTTP adapter refuses. Synthetic dataset: granted by policy. */
export interface DisclosureGrantRequest {
  preview_id: PreviewId;
  payload_digest: Digest;
}

export interface DisclosureGrant {
  grant_id: GrantId;
  kind: "teacher_disclosure";
  recipient: TeacherRecipient;
  dataset_class: DatasetClass;
  fields: TeacherField[];
  item_count: number;
  payload_digest: Digest;
  created_at: Timestamp;
  expires_at: Timestamp;
  revoked_at: NullableTimestamp;
  /** Single use: one grant authorises exactly one teacher request with exactly the previewed payload. */
  used: boolean;
  confirmed_via: "desktop_dialog" | "synthetic_policy";
}

export interface DisclosureGrantResult {
  outcome: "granted" | "declined_by_user" | "refused";
  grant: DisclosureGrant | null;
  refusal: null | "personal_requires_desktop_dialog" | "preview_expired" | "preview_already_used" | "digest_mismatch" | "teacher_unavailable" | "runner_profile_mismatch" | "confinement_not_enforced";
}

export interface RootGrantRecord {
  grant_id: GrantId;
  kind: "metadata_root";
  root_id: RootId;
  granted_at: Timestamp;
  granted_via: "desktop_picker" | "cli_flag" | "fixture";
  revoked_at: NullableTimestamp;
}

export interface GrantList {
  grants: (RootGrantRecord | DisclosureGrant)[];
}

export interface GrantRevokeRequest {
  grant_id: GrantId;
}

export interface GrantRevokeResult {
  grant_id: GrantId;
  revoked_at: Timestamp;
}

/** Sends exactly the payload bound to the grant's digest. No node list is accepted here. */
export interface TeacherRunRequest {
  grant_id: GrantId;
}

export interface TeacherLabel {
  node_id: NodeId;
  label: Label | null;
  abstain: boolean;
  reason: string;
  evidence: TeacherField[];
  data_class: "teacher";
  weight: 0.2;
  requires_review: true;
  autonomy_allowed: false;
}

export interface TeacherResults {
  job_id: JobId;
  state: JobState;
  recipient: TeacherRecipient;
  payload_digest: Digest;
  labels: TeacherLabel[];
  rejected_output: boolean;
  rejection_reason: string | null;
}

export interface TierVolume {
  volume_id: VolumeId;
  display_name: string;
  tier: TierInfo;
  online: boolean;
  writable: boolean | null;
  capacity_bytes: NullableBytes;
  free_bytes: NullableBytes;
  reserve_bytes: ByteCount;
  free_fraction: NullableFraction;
  pressure: "ok" | "watch" | "pressure" | "unknown";
}

export interface TierModel {
  volumes: TierVolume[];
  policy: {
    watch_free_fraction: Fraction;
    pressure_free_fraction: Fraction;
    reserve_note: string;
    note: string;
  };
}

/** mtime_proxy is a labelled what-if only; modification age is not access heat. */
export type HeatBasis = "unknown" | "assumed" | "mtime_proxy";

export type CandidateBasis = "root_children" | "largest_dirs";

export interface PlacementCandidatesRequest {
  source_volume_id: VolumeId;
  basis: CandidateBasis;
  max_groups: number;
  min_bytes: ByteCount;
}

export interface CandidateGroup {
  group_id: GroupId;
  node_id: NodeId;
  root_id: RootId;
  name: string;
  /** Bytes by directory entry under estimate_basis (observation, not relief). */
  source_bytes: ByteCount;
  /** Labelled estimate: per-file logical size rounded up to the destination cluster size where known. */
  destination_bytes: ByteCount;
  transfer_bytes: ByteCount;
  estimate_basis: "allocated_entries" | "logical_fallback" | "unknown";
  /** null unless relief_basis is verified_unique_allocation or an entry_allocation_whatif was requested. */
  estimated_relief_bytes: NullableBytes;
  /** verified_unique_allocation: every entry has a native ID, every object's names are inside this group and link counts were observed; default stream only. */
  relief_basis: "verified_unique_allocation" | "entry_allocation_whatif" | "unknown";
  heat: NullableFraction;
  heat_basis: HeatBasis;
  newest_modified_at: NullableTimestamp;
  pinned: boolean | null;
  active: boolean | null;
  protected: boolean | null;
  days_since_move: number | null;
  coverage: CoverageState;
}

export interface PlacementCandidates {
  source_volume_id: VolumeId;
  root_generations: RootGeneration[];
  groups: CandidateGroup[];
  note: string;
}

/** Owner what-if assumptions, recorded as assumed in the plan. They never change capacities or volumes; those come from observations only. */
export interface GroupOverride {
  group_id: GroupId;
  heat?: NullableFraction;
  pinned?: boolean | null;
  active?: boolean | null;
  protected?: boolean | null;
  days_since_move?: number | null;
}

export interface PlacementSimulateRequest {
  source_volume_id: VolumeId;
  target_free_bytes: ByteCount;
  max_transfer_bytes: ByteCount;
  heat_policy: "unknown_is_ineligible" | "mtime_proxy_whatif" | "assumed_only";
  /** verified_only (default) pre-rejects groups whose relief is unknown; entry_allocation_whatif feeds entry allocation as an assumed relief and records it in assumptions. */
  relief_policy: "verified_only" | "entry_allocation_whatif";
  candidate_basis: CandidateBasis;
  max_groups: number;
  overrides: GroupOverride[];
  node_budget: number;
  save: boolean;
}

export interface PlacementProposal {
  group_id: GroupId;
  source_id: VolumeId;
  target_id: VolumeId;
  source_bytes_relieved: ByteCount;
  destination_bytes_required: ByteCount;
  transfer_bytes: ByteCount;
  reason: "bounded_capacity_budget_allocation";
  requires_consent: true;
  executable: false;
}

/** Field-for-field the planner_v2 output (python/loomward/planner_v2.py) with bytes as decimal strings, plus heat_policy, assumptions, root_generations and proposal_id. */
export interface PlacementPlan {
  mode: "simulation";
  algorithm: "bounded_portfolio_search_v2";
  optimality_claim: boolean;
  optimality_scope: string;
  shortfall_optimal: boolean;
  search: {
    complete: boolean;
    nodes_visited: Count;
    node_budget: Count;
    reason: "exhausted" | "node_budget" | "problem_size_limit";
    eligible_groups: Count;
    eligible_targets: Count;
    lower_bound_shortfall_bytes: ByteCount;
  };
  proposals: PlacementProposal[];
  /** Exactly the planner's own rejections (parity with planner_v2). */
  rejected: ({
    group_id: GroupId;
    reason: "not_on_source" | "pinned_active_protected_or_unspecified" | "heat_unknown" | "not_cold" | "cooldown_or_history_unknown" | "source_offline_or_readonly" | "not_selected_by_bounded_allocator";
  })[];
  /** Service-level exclusions applied before the planner runs; these groups never reach it. */
  pre_rejected: ({
    group_id: GroupId;
    reason: "relief_unknown" | "shares_objects_with_other_group" | "group_coverage_incomplete";
  })[];
  excluded_volumes: ({
    volume_id: VolumeId;
    reason: "tier_unknown" | "capacity_unknown" | "offline";
  })[];
  relief_policy: "verified_only" | "entry_allocation_whatif";
  projected_free_bytes: { [key: string]: ByteCount };
  target_free_bytes: ByteCount;
  shortfall_bytes: ByteCount;
  satisfied: boolean;
  transfer_bytes: ByteCount;
  filesystem_changed: false;
  baseline_shortfall_bytes: ByteCount;
  shortfall_improvement_bytes: ByteCount;
  assumption: string;
  heat_policy: "unknown_is_ineligible" | "mtime_proxy_whatif" | "assumed_only";
  assumptions: string[];
  root_generations: RootGeneration[];
  proposal_id: ProposalId | null;
}

export interface ProposalSummary {
  proposal_id: ProposalId;
  kind: "placement_simulation";
  status: "simulation_only" | "stale";
  created_at: Timestamp;
  source_volume_id: VolumeId;
  satisfied: boolean;
  shortfall_bytes: ByteCount;
}

export interface ProposalList {
  proposals: ProposalSummary[];
}

export interface ProposalRefRequest {
  proposal_id: ProposalId;
}

export interface ProposalDetail {
  summary: ProposalSummary;
  inputs_digest: Digest;
  plan: PlacementPlan;
}

export type TelemetryChannel = "system" | "processes" | "gpu" | "disks" | "engine";

export type TelemetryInterval = 1000 | 2000 | 5000 | 10000;

export interface TelemetrySubscribeRequest {
  /** null creates; an existing id renews and may change channels/interval. */
  subscription_id: SubscriptionId | null;
  channels: TelemetryChannel[];
  interval_ms: TelemetryInterval;
}

export interface TelemetrySubscription {
  subscription_id: SubscriptionId;
  channels: TelemetryChannel[];
  interval_ms: TelemetryInterval;
  /** 60 s lease; the sampler stops when no live subscription remains. */
  expires_at: Timestamp;
}

export interface SubscriptionRefRequest {
  subscription_id: SubscriptionId;
}

export interface TelemetryUnsubscribed {
  subscription_id: SubscriptionId;
  stopped: boolean;
}

export interface TelemetrySnapshotRequest {
  channels: TelemetryChannel[];
}

export interface SystemSample {
  memory: {
    total_bytes: NullableBytes;
    available_bytes: NullableBytes;
    commit_bytes: NullableBytes;
    commit_limit_bytes: NullableBytes;
    load_fraction: NullableFraction;
  };
  cpu: {
    logical_cpus: Count;
    busy_fraction: NullableFraction;
  };
}

export interface GpuSample {
  state: "observed" | "unavailable" | "denied";
  basis: "pdh_gpu_counters" | "unavailable";
  adapters: {
    adapter_id: string;
    name: string;
    dedicated_total_bytes: NullableBytes;
    /** Global, from the GPU Adapter Memory counter; never a sum of per-process values. */
    dedicated_used_bytes: NullableBytes;
    /** Global, from the GPU Adapter Memory counter. */
    shared_used_bytes: NullableBytes;
    /** Maximum over engine types of the per-type utilisation summed across that adapter's engine instances, clamped to 1 (the Task Manager method). */
    engine_busy_fraction: NullableFraction;
  }[];
}

export interface DiskSample {
  state: "observed" | "unavailable";
  disks: {
    disk_label: string;
    volume_ids: VolumeId[];
    read_bytes_per_s: NullableRate;
    write_bytes_per_s: NullableRate;
    /** 1 - (PhysicalDisk % Idle Time / 100), clamped to [0, 1]. */
    busy_fraction: NullableFraction;
    /** PhysicalDisk Avg. Disk Queue Length; a separate quantity from busy_fraction. */
    queue_length: NullableRate;
  }[];
}

export type PoolName = "scan_enumerate" | "catalog_write" | "learning" | "teacher" | "telemetry";

export interface PoolUse {
  pool: PoolName;
  max_workers: number;
  busy_workers: number;
  queue_depth: Count;
  queue_capacity: Count;
}

export interface EngineSample {
  private_commit_bytes: NullableBytes;
  working_set_bytes: NullableBytes;
  /** Machine-normalised: CPU time over the interval divided by (interval x logical CPUs). */
  cpu_fraction: NullableFraction;
  threads: NullableCount;
  pools: PoolUse[];
}

/** No command line, no environment, no window titles (privacy). */
export interface ProcessRow {
  process_ref: ProcessRef;
  pid: number;
  name: string;
  started_at: NullableTimestamp;
  /** PROCESS_MEMORY_COUNTERS_EX2.PrivateUsage (commit charge), not resident memory. */
  private_commit_bytes: NullableBytes;
  /** PROCESS_MEMORY_COUNTERS_EX2.PrivateWorkingSetSize where supported, else null. */
  private_working_set_bytes: NullableBytes;
  /** Total working set, including shared pages. */
  working_set_bytes: NullableBytes;
  /** Machine-normalised over the sample interval; null on the first sample. */
  cpu_fraction: NullableFraction;
  io_read_bytes_per_s: NullableRate;
  io_write_bytes_per_s: NullableRate;
  /** GPU Process Memory dedicated usage for this process; may include shared allocations, so rows are never summed into an adapter total. */
  gpu_dedicated_bytes: NullableBytes;
  access: "full" | "limited" | "denied";
  loomward_owned: boolean;
}

export interface ProcessSummary {
  observed_count: Count;
  denied_count: Count;
  top: ProcessRow[];
}

export interface TelemetrySample {
  sample_seq: Count;
  observed_at: Timestamp;
  /** Monotonic time since the previous sample; null on the first sample. */
  elapsed_ms: NullableCount;
  system: SystemSample | null;
  gpu: GpuSample | null;
  disks: DiskSample | null;
  engine: EngineSample | null;
  processes: ProcessSummary | null;
}

export interface ProcessListRequest {
  sort: "private_desc" | "working_set_desc" | "cpu_desc" | "io_desc" | "gpu_desc" | "name_asc";
  limit: number;
}

export interface ProcessList {
  sample_seq: Count;
  observed_at: Timestamp;
  rows: ProcessRow[];
  observed_count: Count;
  denied_count: Count;
  truncated: boolean;
  note: string;
}

export interface ProcessRefRequest {
  process_ref: ProcessRef;
}

export interface ProcessExplanation {
  process_ref: ProcessRef;
  observed_at: Timestamp;
  facts: {
    code: string;
    text: string;
  }[];
  summary: string;
  caveats: string[];
  /** Always empty in v0.3 (invariant 1). */
  available_actions: never[];
}

export interface PoolBudget {
  pool: PoolName;
  max_workers: number;
  default_workers: number;
  current_workers: number;
  queue_capacity: Count;
  scope: "loomward_own_threads";
}

export interface OwnBudgets {
  pools: PoolBudget[];
  teacher: {
    max_in_flight: 1;
    timeout_s: number;
    memory_limit_bytes: NullableBytes;
    enforcement: "job_object" | "not_available";
  };
  enforcement_note: string;
}

/** Caps Loomward's own in-process pools only. No OS priority, affinity or memory call is made. */
export interface BudgetSetRequest {
  pool: "scan_enumerate" | "learning" | "telemetry";
  max_workers: number;
}

export interface StreamHello {
  session_started_at: Timestamp;
  epoch: StreamEpoch;
  last_seq: Count;
  oldest_replayable_seq: Count;
  dataset_class: DatasetClass;
}

export interface StreamLagged {
  reason: "subscriber_overflow" | "epoch_changed" | "replay_gap";
  /** null when unknown (epoch change or replay gap). */
  dropped: NullableCount;
  resync: ("roots" | "volumes" | "jobs" | "tree" | "learning")[];
}

export interface ScanProgressEvent {
  job_id: JobId;
  root_id: RootId;
  progress: ScanProgress;
}

export interface TreeInvalidated {
  root_id: RootId | null;
  generation: NullableGeneration;
  scope: "all" | "nodes";
  node_ids: NodeId[];
}

export interface TelemetrySampleEvent {
  subscription_id: SubscriptionId;
  sample: TelemetrySample;
}

export interface LearningUpdated {
  status: LearningStatus;
}

// ---- commands (commands.json)

export interface CommandMap {
  "session.hello": { request: EmptyRequest; result: SessionInfo };
  "health.get": { request: EmptyRequest; result: Health };
  "roots.list": { request: EmptyRequest; result: RootList };
  "roots.request_grant": { request: RootGrantRequest; result: RootGrantResult };
  "roots.revoke": { request: RootRevokeRequest; result: RootRevokeResult };
  "volumes.list": { request: EmptyRequest; result: VolumeList };
  "volumes.declare_tier": { request: DeclareTierRequest; result: DeclareTierResult };
  "scan.start": { request: ScanStartRequest; result: JobResult };
  "scan.cancel": { request: JobRefRequest; result: JobResult };
  "jobs.get": { request: JobRefRequest; result: JobResult };
  "jobs.list": { request: JobListRequest; result: JobList };
  "tree.slice": { request: TreeSliceRequest; result: TreeSlice };
  "tree.children": { request: TreeChildrenRequest; result: EntryPage };
  "tree.path": { request: NodeRefRequest; result: NodePath };
  "node.inspect": { request: NodeRefRequest; result: NodeDetail };
  "threads.meaning": { request: MeaningRequest; result: MeaningResult };
  "search.query": { request: SearchRequest; result: EntryPage };
  "stats.breakdown": { request: BreakdownRequest; result: Breakdown };
  "taxonomy.get": { request: EmptyRequest; result: Taxonomy };
  "feedback.record": { request: FeedbackRequest; result: FeedbackResult };
  "learning.status": { request: EmptyRequest; result: LearningStatus };
  "learning.queue": { request: LearningQueueRequest; result: LearningQueue };
  "learning.refit": { request: EmptyRequest; result: JobResult };
  "collections.list": { request: EmptyRequest; result: CollectionList };
  "collections.create": { request: CollectionCreateRequest; result: Collection };
  "collections.update_members": { request: CollectionMembersUpdate; result: Collection };
  "collections.members": { request: CollectionMembersRequest; result: EntryPage };
  "teacher.preview": { request: TeacherPreviewRequest; result: TeacherPreview };
  "grants.list": { request: EmptyRequest; result: GrantList };
  "grants.create_disclosure": { request: DisclosureGrantRequest; result: DisclosureGrantResult };
  "grants.revoke": { request: GrantRevokeRequest; result: GrantRevokeResult };
  "teacher.run": { request: TeacherRunRequest; result: JobResult };
  "teacher.results": { request: JobRefRequest; result: TeacherResults };
  "tiers.model": { request: EmptyRequest; result: TierModel };
  "placement.candidates": { request: PlacementCandidatesRequest; result: PlacementCandidates };
  "placement.simulate": { request: PlacementSimulateRequest; result: PlacementPlan };
  "proposals.list": { request: EmptyRequest; result: ProposalList };
  "proposals.get": { request: ProposalRefRequest; result: ProposalDetail };
  "telemetry.subscribe": { request: TelemetrySubscribeRequest; result: TelemetrySubscription };
  "telemetry.unsubscribe": { request: SubscriptionRefRequest; result: TelemetryUnsubscribed };
  "telemetry.snapshot": { request: TelemetrySnapshotRequest; result: TelemetrySample };
  "processes.list": { request: ProcessListRequest; result: ProcessList };
  "processes.explain": { request: ProcessRefRequest; result: ProcessExplanation };
  "budgets.get": { request: EmptyRequest; result: OwnBudgets };
  "budgets.set": { request: BudgetSetRequest; result: OwnBudgets };
}

export type CommandKey = keyof CommandMap;

/** Where each command exists (elsewhere: capability_unavailable), its wave and its events. */
export const COMMANDS = {
  "session.hello": { adapters: ["tauri", "http"], wave: 1, events: [] },
  "health.get": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "roots.list": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "roots.request_grant": { adapters: ["tauri"], wave: 2, events: [] },
  "roots.revoke": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "volumes.list": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "volumes.declare_tier": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "scan.start": { adapters: ["tauri", "http"], wave: 2, events: ["job.state", "scan.progress", "tree.invalidated"] },
  "scan.cancel": { adapters: ["tauri", "http"], wave: 2, events: ["job.state"] },
  "jobs.get": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "jobs.list": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "tree.slice": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "tree.children": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "tree.path": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "node.inspect": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "threads.meaning": { adapters: ["tauri", "http"], wave: 3, events: [] },
  "search.query": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "stats.breakdown": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "taxonomy.get": { adapters: ["tauri", "http"], wave: 3, events: [] },
  "feedback.record": { adapters: ["tauri", "http"], wave: 3, events: ["learning.updated"] },
  "learning.status": { adapters: ["tauri", "http"], wave: 3, events: [] },
  "learning.queue": { adapters: ["tauri", "http"], wave: 3, events: [] },
  "learning.refit": { adapters: ["tauri", "http"], wave: 3, events: ["job.state", "learning.updated"] },
  "collections.list": { adapters: ["tauri", "http"], wave: 3, events: [] },
  "collections.create": { adapters: ["tauri", "http"], wave: 3, events: [] },
  "collections.update_members": { adapters: ["tauri", "http"], wave: 3, events: [] },
  "collections.members": { adapters: ["tauri", "http"], wave: 3, events: [] },
  "teacher.preview": { adapters: ["tauri", "http"], wave: 3, events: [] },
  "grants.list": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "grants.create_disclosure": { adapters: ["tauri", "http"], wave: 3, events: [] },
  "grants.revoke": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "teacher.run": { adapters: ["tauri", "http"], wave: 3, events: ["job.state", "learning.updated"] },
  "teacher.results": { adapters: ["tauri", "http"], wave: 3, events: [] },
  "tiers.model": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "placement.candidates": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "placement.simulate": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "proposals.list": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "proposals.get": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "telemetry.subscribe": { adapters: ["tauri", "http"], wave: 2, events: ["telemetry.sample"] },
  "telemetry.unsubscribe": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "telemetry.snapshot": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "processes.list": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "processes.explain": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "budgets.get": { adapters: ["tauri", "http"], wave: 2, events: [] },
  "budgets.set": { adapters: ["tauri", "http"], wave: 2, events: [] },
} as const satisfies Record<CommandKey, {
  adapters: readonly ("tauri" | "http")[];
  wave: number;
  events: readonly EventKey[];
}>;

export const COMMAND_NAMES = Object.keys(COMMANDS) as CommandKey[];

// ---- events (commands.json)

export interface EventMap {
  "stream.hello": StreamHello;
  "stream.lagged": StreamLagged;
  "job.state": JobResult;
  "scan.progress": ScanProgressEvent;
  "tree.invalidated": TreeInvalidated;
  "telemetry.sample": TelemetrySampleEvent;
  "learning.updated": LearningUpdated;
  "roots.changed": RootList;
  "volumes.changed": VolumeList;
  "health.warning": HealthWarning;
}

export type EventKey = keyof EventMap;

export const EVENT_NAMES = ["stream.hello", "stream.lagged", "job.state", "scan.progress", "tree.invalidated", "telemetry.sample", "learning.updated", "roots.changed", "volumes.changed", "health.warning"] as const satisfies readonly EventKey[];

// ---- typed envelopes
export interface TypedRequest<C extends CommandKey> extends Omit<RequestEnvelope, "command" | "payload"> {
  command: C;
  payload: CommandMap[C]["request"];
}

export interface TypedResponseOk<C extends CommandKey> extends Omit<ResponseOk, "result"> {
  result: CommandMap[C]["result"];
}

export type TypedResponse<C extends CommandKey> = TypedResponseOk<C> | ResponseError;

export interface TypedEvent<E extends EventKey> extends Omit<EventEnvelope, "event" | "data"> {
  event: E;
  data: EventMap[E];
}
