#!/usr/bin/env python3
"""Generate app/src/lib/contracts.gen.ts from contracts/v3/ (docs/41 section 5, LW-103).

Emits one TypeScript type per `$defs` entry of view-service.schema.json plus `CommandMap`,
`EventMap` and the closed name lists from commands.json. Deterministic: same inputs, same
bytes, LF newlines. Standard library only.

    py -3 scripts/gen_contracts_ts.py           # write the file
    py -3 scripts/gen_contracts_ts.py --check   # exit 1 if the committed file is stale
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "contracts" / "v3" / "view-service.schema.json"
COMMANDS = ROOT / "contracts" / "v3" / "commands.json"
OUT = ROOT / "app" / "src" / "lib" / "contracts.gen.ts"

HEADER = """// GENERATED by scripts/gen_contracts_ts.py from contracts/v3/view-service.schema.json and
// contracts/v3/commands.json (protocol {protocol}). Do not edit; run
// `py -3 scripts/gen_contracts_ts.py` and commit the result.
//
// Byte quantities are decimal strings (`ByteCount`); `null` means unknown, never zero.
// Counts are JSON integers below 2^53. No request carries a path. A type match is never
// permission: the service re-validates scope, grants and bounds.
"""


def lit(value):
    return json.dumps(value, ensure_ascii=False)


def ident(name):
    return name if name.isidentifier() else lit(name)


def union(parts):
    seen = []
    for p in parts:
        if p not in seen:
            seen.append(p)
    return " | ".join(seen) if seen else "never"


def ts_type(node, indent):
    """TypeScript for one schema node; `indent` is the nesting depth of the line it sits on."""
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]
    for key in ("anyOf", "oneOf"):
        if key in node:
            return union(ts_type(alt, indent) for alt in node[key])
    if "const" in node:
        return lit(node["const"])
    if "enum" in node:
        return union(lit(v) for v in node["enum"])
    t = node.get("type")
    if isinstance(t, list):
        return union(ts_type({**node, "type": one}, indent) for one in t)
    if t == "null":
        return "null"
    if t == "boolean":
        return "boolean"
    if t in ("integer", "number"):
        return "number"
    if t == "string":
        return "string"
    if t == "array":
        if "items" not in node:
            return "never[]"
        item = ts_type(node["items"], indent)
        return f"({item})[]" if " | " in item else f"{item}[]"
    if t == "object":
        props = node.get("properties")
        if props:
            return object_body(node, indent)
        extra = node.get("additionalProperties")
        if isinstance(extra, dict):
            return f"{{ [key: string]: {ts_type(extra, indent)} }}"
        return "Record<string, unknown>"
    raise ValueError(f"unsupported schema node: {node!r}")


def object_body(node, indent):
    pad = "  " * (indent + 1)
    required = set(node.get("required", []))
    lines = ["{"]
    for name, prop in node["properties"].items():
        if "$comment" in prop:
            lines.append(f"{pad}/** {prop['$comment']} */")
        opt = "" if name in required else "?"
        lines.append(f"{pad}{ident(name)}{opt}: {ts_type(prop, indent + 1)};")
    lines.append("  " * indent + "}")
    return "\n".join(lines)


def emit_def(name, node):
    out = []
    if "$comment" in node:
        out.append(f"/** {node['$comment']} */")
    if node.get("type") == "object" and node.get("properties"):
        out.append(f"export interface {name} {object_body(node, 0)}")
    else:
        out.append(f"export type {name} = {ts_type(node, 0)};")
    return "\n".join(out)


def render():
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    cmds = json.loads(COMMANDS.read_text(encoding="utf-8"))
    protocol = cmds["protocol"]
    parts = [HEADER.format(protocol=protocol), f'export const PROTOCOL = {lit(protocol)};\n']
    parts.append("// ---- $defs\n")
    for name, node in schema["$defs"].items():
        parts.append(emit_def(name, node) + "\n")

    parts.append("// ---- commands (commands.json)\n")
    rows = []
    meta = []
    for name, c in cmds["commands"].items():
        rows.append(f"  {lit(name)}: {{ request: {c['request']}; result: {c['result']} }};")
        events = ", ".join(lit(e) for e in c.get("events", []))
        adapters = ", ".join(lit(a) for a in c["adapters"])
        meta.append(
            f"  {lit(name)}: {{ adapters: [{adapters}], wave: {c['wave']}, events: [{events}] }},"
        )
    parts.append("export interface CommandMap {\n" + "\n".join(rows) + "\n}\n")
    parts.append("export type CommandKey = keyof CommandMap;\n")
    parts.append(
        "/** Where each command exists (elsewhere: capability_unavailable), its wave and its events. */\n"
        "export const COMMANDS = {\n" + "\n".join(meta) + "\n} as const satisfies Record<CommandKey, {\n"
        '  adapters: readonly ("tauri" | "http")[];\n  wave: number;\n  events: readonly EventKey[];\n}>;\n'
    )
    parts.append(
        "export const COMMAND_NAMES = Object.keys(COMMANDS) as CommandKey[];\n"
    )

    parts.append("// ---- events (commands.json)\n")
    erows = [f"  {lit(n)}: {e['data']};" for n, e in cmds["events"].items()]
    parts.append("export interface EventMap {\n" + "\n".join(erows) + "\n}\n")
    parts.append("export type EventKey = keyof EventMap;\n")
    names = ", ".join(lit(n) for n in cmds["events"])
    parts.append(f"export const EVENT_NAMES = [{names}] as const satisfies readonly EventKey[];\n")

    parts.append(
        """// ---- typed envelopes
export interface TypedRequest<C extends CommandKey> extends Omit<RequestEnvelope, "command" | "payload"> {
  command: C;
  payload: CommandMap[C]["request"];
}

export interface TypedResponseOk<C extends CommandKey> extends Omit<ResponseOk, "result"> {
  result: CommandMap[C]["result"];
}

export type TypedResponse<C extends CommandKey> = TypedResponseOk<C> | ResponseError;

export interface TypedEvent<E extends EventKey> extends Omit<EventEnvelope, "event" | "data"> {
  event: E;
  data: EventMap[E];
}
"""
    )
    return "\n".join(parts)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="fail if the committed file differs")
    args = ap.parse_args()
    text = render()
    if args.check:
        current = OUT.read_bytes().decode("utf-8").replace("\r\n", "\n") if OUT.exists() else None
        if current != text:
            why = "missing" if current is None else "stale"
            print(f"{OUT.relative_to(ROOT)} is {why}: run py -3 scripts/gen_contracts_ts.py", file=sys.stderr)
            return 1
        print(f"{OUT.relative_to(ROOT)} is up to date")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_bytes(text.encode("utf-8"))
    print(f"wrote {OUT.relative_to(ROOT)} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
